import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://www.bhansalimetals.com',
  output: 'static',
  build: {
    format: 'directory',
  },
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.8,
      lastmod: new Date(),
    }),
  ],
  redirects: {
    '/aboutus.html': '/about',
    '/certificates.html': '/certificates',
    '/quality.html': '/quality',
    '/contactus.html': '/contact',
    '/enquiry.html': '/rfq',
    '/product.html': '/products/round-bars',
    '/product_black.html': '/products/round-bars',
    '/rodbar.html': '/products/round-bars',
    '/sheetplate.html': '/products/sheets-plates',
    '/stainless.html': '/products/flanges',
    '/stanless_fastnrs.html': '/products/fasteners',
    '/fastener.html': '/products/fasteners',
    '/stanless_pipe.html': '/products/pipes-tubes',
    '/pipefitting.html': '/products/buttweld-fittings',
    '/highnickel.html': '/alloys/inconel-600',
    '/monel500.html': '/alloys/monel-k500',
    '/hastelloyc-276.html': '/alloys/hastelloy-c276',
    '/hastelloyc-22.html': '/alloys/hastelloy-c22',
    '/hastelloyc-b2.html': '/alloys/hastelloy-b2',
    '/hastelloyc-x.html': '/alloys/hastelloy-x',
    '/nickel200-201.html': '/alloys/nickel-200',
    '/technical.html': '/technical-data/stainless-chemical-composition',
    '/tech_new_demo.html': '/technical-data/international-equivalents',
    '/Tech_mechanical.html': '/technical-data/mechanical-properties',
    '/tech_pipefitting.html': '/products/buttweld-fittings',
    '/tech_forgedfitting.html': '/products/forged-fittings',
    '/tech_elbow.html': '/technical-data/elbow-dimensions',
    '/tech_stubend.html': '/technical-data/stub-end-dimensions',
    '/tech_tees.html': '/technical-data/tee-dimensions',
    '/tech_reducer.html': '/technical-data/reducer-dimensions',
    '/tech_caps.html': '/technical-data/cap-dimensions',
    '/tech_round.html': '/technical-data/bar-tolerances',
    '/tech_pipedata.html': '/technical-data/pipe-schedule-chart',
    '/tech_nickelalloy.html': '/technical-data/nickel-chemical-composition',
    '/tech_flanges.html': '/technical-data/asme-b16-5-flanges',
    '/tech_wg_formula.html': '/technical-data/theoretical-weight-formulas',
    '/tech_nonferrous.html': '/technical-data/non-ferrous-weights',
  },
});
